apiVersion: v1
kind: Service
metadata:
  name:  twitter-trend-service
  namespace: twitter
  labels:
    name: twitter-t
spec:
  type: NodePort
  selector:
    app: twitter-trend
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
